### ISSUE TITLE
Error creating redfish client app=redfish_exporter

### ISSUE THREAD

**Issue by tarekradi** [jenningsloy318/redfish_exporter#33]
``Hi. I am stuck. 

Goal = Trying to use the redfish_exporter to load sensor data from BMC via redfish and track that sensor data in Prometheus.

Setup = 
- Prometheus service running on CentOS host with IP 10.219.111.125. 
- This is a CentOS Linux release 8.4.2105
- That host's BMC IP is 10.219.111.126. This is where i want to send redfish commands to load up sensor data.
- The redfish_exporter's config yml file lists 10.219.111.126 , and includes the username and password to enter the BMC. 
- I am able to point the host machine's browser to 10.219.111.125:9090 and it loads Prometheus 
- I am able to point the host machine's browser to 10.219.111.125:9610 and it shows the redfish_exporter UI
- In that redfish_exporter UI , i can enter 10.219.111.126 and it loads up data, but i noticed it say "redfish_up 0"

Problem = I keep seeing the following error
error creating redfish client app=redfish_exporter error=Get "https://10.219.111.125/redfish/v1": proxyconnect tcp: tls: first record does not look like a TLS handshake target=10.219.111.125

Prometheus is running as a service. In /etc/prometheus/prometheus.yml i have the following section...
```
  - job_name: 'redfish-exporter'

    # metrics_path defaults to '/metrics'
    metrics_path: /redfish

    # scheme defaults to 'http'.

    static_configs:
    - targets:
       - 10.219.111.125
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9610  ### the address of the redfish-exporter address
      # (optional) when using group config add this to have group=my_group_name
      # target_label: __param_group
       # replacement: my_group_name
```

What am i doing wrong? 
Thank you for your help!
