### ISSUE TITLE
Need more clarification on redfish_exporter setup with Prometheus

### ISSUE THREAD

**Issue by tarekradi** [jenningsloy318/redfish_exporter#34]
Hi, it is not clear how Prometheus and redfish_exporter communicate together. I believe this is done via prometheus.yml. As per README, i see we need this section. 

```
  - job_name: 'redfish-exporter'

    # metrics_path defaults to '/metrics'
    metrics_path: /redfish

    # scheme defaults to 'http'.

    static_configs:
    - targets:
       - 10.36.48.24
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9610  ### the address of the redfish-exporter address
      # (optional) when using group config add this to have group=my_group_name
      - target_label: __param_group
        replacement: my_group_name

```

What parts here are variables that i need to fill in other than the target ip? 

Note that I can successfully call...
` http://10.219.111.125:9610/redfish?target=10.219.111.126&group=`

This seems to scrape the target successfully and returns redfish_up 1, but Prometheus is showing redfish_up = 0 every time! Please help!
